/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EncuestaIdRouteImport } from './routes/encuesta.$id'
import { Route as AuthenticatedSesionRouteImport } from './routes/_authenticated/sesion'
import { Route as AuthenticatedResultadosRouteImport } from './routes/_authenticated/resultados'
import { Route as AuthenticatedEncuestasRouteImport } from './routes/_authenticated/encuestas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConsentimientosRouteImport } from './routes/_authenticated/consentimientos'
import { Route as AuthenticatedEncuestasIdResultadosRouteImport } from './routes/_authenticated/encuestas_.$id.resultados'
import { Route as AuthenticatedEncuestasIdEditRouteImport } from './routes/_authenticated/encuestas_.$id.edit'
import { Route as AuthenticatedConsentimientosIdEditRouteImport } from './routes/_authenticated/consentimientos_.$id.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EncuestaIdRoute = EncuestaIdRouteImport.update({
  id: '/encuesta/$id',
  path: '/encuesta/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSesionRoute = AuthenticatedSesionRouteImport.update({
  id: '/sesion',
  path: '/sesion',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResultadosRoute = AuthenticatedResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEncuestasRoute = AuthenticatedEncuestasRouteImport.update({
  id: '/encuestas',
  path: '/encuestas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConsentimientosRoute =
  AuthenticatedConsentimientosRouteImport.update({
    id: '/consentimientos',
    path: '/consentimientos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEncuestasIdResultadosRoute =
  AuthenticatedEncuestasIdResultadosRouteImport.update({
    id: '/encuestas_/$id/resultados',
    path: '/encuestas/$id/resultados',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEncuestasIdEditRoute =
  AuthenticatedEncuestasIdEditRouteImport.update({
    id: '/encuestas_/$id/edit',
    path: '/encuestas/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConsentimientosIdEditRoute =
  AuthenticatedConsentimientosIdEditRouteImport.update({
    id: '/consentimientos_/$id/edit',
    path: '/consentimientos/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/consentimientos': typeof AuthenticatedConsentimientosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/encuestas': typeof AuthenticatedEncuestasRoute
  '/resultados': typeof AuthenticatedResultadosRoute
  '/sesion': typeof AuthenticatedSesionRoute
  '/encuesta/$id': typeof EncuestaIdRoute
  '/consentimientos/$id/edit': typeof AuthenticatedConsentimientosIdEditRoute
  '/encuestas/$id/edit': typeof AuthenticatedEncuestasIdEditRoute
  '/encuestas/$id/resultados': typeof AuthenticatedEncuestasIdResultadosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/consentimientos': typeof AuthenticatedConsentimientosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/encuestas': typeof AuthenticatedEncuestasRoute
  '/resultados': typeof AuthenticatedResultadosRoute
  '/sesion': typeof AuthenticatedSesionRoute
  '/encuesta/$id': typeof EncuestaIdRoute
  '/consentimientos/$id/edit': typeof AuthenticatedConsentimientosIdEditRoute
  '/encuestas/$id/edit': typeof AuthenticatedEncuestasIdEditRoute
  '/encuestas/$id/resultados': typeof AuthenticatedEncuestasIdResultadosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/consentimientos': typeof AuthenticatedConsentimientosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/encuestas': typeof AuthenticatedEncuestasRoute
  '/_authenticated/resultados': typeof AuthenticatedResultadosRoute
  '/_authenticated/sesion': typeof AuthenticatedSesionRoute
  '/encuesta/$id': typeof EncuestaIdRoute
  '/_authenticated/consentimientos_/$id/edit': typeof AuthenticatedConsentimientosIdEditRoute
  '/_authenticated/encuestas_/$id/edit': typeof AuthenticatedEncuestasIdEditRoute
  '/_authenticated/encuestas_/$id/resultados': typeof AuthenticatedEncuestasIdResultadosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/consentimientos'
    | '/dashboard'
    | '/encuestas'
    | '/resultados'
    | '/sesion'
    | '/encuesta/$id'
    | '/consentimientos/$id/edit'
    | '/encuestas/$id/edit'
    | '/encuestas/$id/resultados'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/consentimientos'
    | '/dashboard'
    | '/encuestas'
    | '/resultados'
    | '/sesion'
    | '/encuesta/$id'
    | '/consentimientos/$id/edit'
    | '/encuestas/$id/edit'
    | '/encuestas/$id/resultados'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/consentimientos'
    | '/_authenticated/dashboard'
    | '/_authenticated/encuestas'
    | '/_authenticated/resultados'
    | '/_authenticated/sesion'
    | '/encuesta/$id'
    | '/_authenticated/consentimientos_/$id/edit'
    | '/_authenticated/encuestas_/$id/edit'
    | '/_authenticated/encuestas_/$id/resultados'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  EncuestaIdRoute: typeof EncuestaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encuesta/$id': {
      id: '/encuesta/$id'
      path: '/encuesta/$id'
      fullPath: '/encuesta/$id'
      preLoaderRoute: typeof EncuestaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sesion': {
      id: '/_authenticated/sesion'
      path: '/sesion'
      fullPath: '/sesion'
      preLoaderRoute: typeof AuthenticatedSesionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resultados': {
      id: '/_authenticated/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof AuthenticatedResultadosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/encuestas': {
      id: '/_authenticated/encuestas'
      path: '/encuestas'
      fullPath: '/encuestas'
      preLoaderRoute: typeof AuthenticatedEncuestasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/consentimientos': {
      id: '/_authenticated/consentimientos'
      path: '/consentimientos'
      fullPath: '/consentimientos'
      preLoaderRoute: typeof AuthenticatedConsentimientosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/encuestas_/$id/resultados': {
      id: '/_authenticated/encuestas_/$id/resultados'
      path: '/encuestas/$id/resultados'
      fullPath: '/encuestas/$id/resultados'
      preLoaderRoute: typeof AuthenticatedEncuestasIdResultadosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/encuestas_/$id/edit': {
      id: '/_authenticated/encuestas_/$id/edit'
      path: '/encuestas/$id/edit'
      fullPath: '/encuestas/$id/edit'
      preLoaderRoute: typeof AuthenticatedEncuestasIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/consentimientos_/$id/edit': {
      id: '/_authenticated/consentimientos_/$id/edit'
      path: '/consentimientos/$id/edit'
      fullPath: '/consentimientos/$id/edit'
      preLoaderRoute: typeof AuthenticatedConsentimientosIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedConsentimientosRoute: typeof AuthenticatedConsentimientosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEncuestasRoute: typeof AuthenticatedEncuestasRoute
  AuthenticatedResultadosRoute: typeof AuthenticatedResultadosRoute
  AuthenticatedSesionRoute: typeof AuthenticatedSesionRoute
  AuthenticatedConsentimientosIdEditRoute: typeof AuthenticatedConsentimientosIdEditRoute
  AuthenticatedEncuestasIdEditRoute: typeof AuthenticatedEncuestasIdEditRoute
  AuthenticatedEncuestasIdResultadosRoute: typeof AuthenticatedEncuestasIdResultadosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedConsentimientosRoute: AuthenticatedConsentimientosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEncuestasRoute: AuthenticatedEncuestasRoute,
  AuthenticatedResultadosRoute: AuthenticatedResultadosRoute,
  AuthenticatedSesionRoute: AuthenticatedSesionRoute,
  AuthenticatedConsentimientosIdEditRoute:
    AuthenticatedConsentimientosIdEditRoute,
  AuthenticatedEncuestasIdEditRoute: AuthenticatedEncuestasIdEditRoute,
  AuthenticatedEncuestasIdResultadosRoute:
    AuthenticatedEncuestasIdResultadosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  EncuestaIdRoute: EncuestaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
